### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by halturin** [sdil/goakt-realtimemap#1]
came across goakt project and found your issue there. Just wondering if there is a chance to the see the same benchmark but using Ergo Framework (see demo example here https://github.com/ergo-services/examples/tree/v300). 
PS: v.3 is about to release, so those examples are pointed to the commit in v300 branch of https://github.com/ergo-services/ergo
PPS: you may also want to see the benchmarks https://github.com/ergo-services/benchmarks

**Comment by sdil** [comment]
Thanks @halturin! I was evaluating ergo system as well. I might be able to do the same hopefully in the future :D

**Comment by halturin** [comment]
thanks for swift response. the previous verion (2.*) wasnt good enough, so dont expect any good result with it :). use v300 branch. its way more performant.

PS adjust the number of workers in pool as you need here https://github.com/ergo-services/examples/blob/v300/demo/apps/myapp/mypool.go#L20
and here add your logic https://github.com/ergo-services/examples/blob/v300/demo/apps/myapp/mypool_web_worker.go

and here you can configure host:port for the web server https://github.com/ergo-services/examples/blob/v300/demo/apps/myapp/myweb.go#L41

you also can see the metrics in the observer (this app is embedded there, just open http://localhost:9911, go to the "Processes" page, find "pool" process, open the process page - there you will see charts with num msg/sec, queue metrics). Like this one https://x.com/halturin/status/1802801540216054040?s=46&t=a-KSHQlLDlsyfI8bjFDfng

**Comment by sdil** [comment]
Exciting :heart_eyes:

Can I use the net http lib or go gin together with ergo service?

**Comment by halturin** [comment]
sure, that example uses standard mux https://github.com/ergo-services/examples/blob/v300/demo/apps/myapp/myweb.go#L22 

you can use gin as well

**Comment by sdil** [comment]
I'm trying to rebuild this app using ergo but the documentation is missing and it feels abit difficult to me to. write without documentation. I understand that you'll release v3 in September. I'll continue working on this once you released the new version. It will be committed to this repo btw https://github.com/sdil/ergo-realtimemap :)

**Comment by halturin** [comment]
https://docs.ergo.services

**Comment by sdil** [comment]
@halturin it might be my skill issue but I'm not sure how to:

1. create/spawn an actor from web worker
2. create/spawn an actor when an application starts
3. how to send/call an actor from web worker

1 more question, does ergo is intended to be a stateful actor system? i'm not too sure how to keep the state in actor (in this case latitude & longitude of the vehicle)

appreciate if you can help me with that 🙇

**Comment by halturin** [comment]
@sdil thanks for the questions

1. not sure i follow the question. please, provide more details what exact you are trying to do
2. application is just an umbrella to start a set of actors. see documentation https://docs.ergo.services/basics/application
3. any actor based on act.Actor has embedded gen.Process interface, so you can use all those methods. to send a message use `Send`, to make a request - use `Call`

yes, actors are stateful. for example
```
type myActor struct {
   act.Actor
   // every actor has its own instance of this struct, so this is the internal state of this actor 
  // and belong to the particular process. nobody can access to this values. spawned process only
   lat int64
   lon int64
} 

func factoryMyActor() gen.ProcessBehavior {
	return &myActor{}
}

...

// use gen.Process or gen.Node interface to spawn your actor
```

**Comment by sdil** [comment]
Closing this because of skill issue
